// Generated from cmdevents.cpp; do not edit
#include "wxvbam.h"

struct cmditem cmdtab[] = {
    {wxT("ABOUT"), wxTRANSLATE("About..."), wxID_ABOUT },
    {wxT("BugReport"), wxTRANSLATE("Report bugs..."), XRCID("BugReport") },
    {wxT("CLOSE"), wxTRANSLATE("Close"), wxID_CLOSE, CMDEN_GB|CMDEN_GBA },
    {wxT("ChangeFilter"), wxTRANSLATE("Change Pixel Filter"), XRCID("ChangeFilter"), CMDEN_NREC_ANY },
    {wxT("ChangeIFB"), wxTRANSLATE("Change Interframe Blending"), XRCID("ChangeIFB"), CMDEN_NREC_ANY },
    {wxT("CheatsAutoSaveLoad"), wxTRANSLATE("Auto save/load cheats (toggle)"), XRCID("CheatsAutoSaveLoad") },
    {wxT("CheatsEnable"), wxTRANSLATE("Enable cheats (toggle)"), XRCID("CheatsEnable") },
    {wxT("CheatsList"), wxTRANSLATE("List cheats..."), XRCID("CheatsList"), CMDEN_GB|CMDEN_GBA },
    {wxT("CheatsSearch"), wxTRANSLATE("Create cheat..."), XRCID("CheatsSearch"), CMDEN_GB|CMDEN_GBA },
    {wxT("Customize"), wxTRANSLATE("Customize UI..."), XRCID("Customize") },
    {wxT("DebugGDB"), wxTRANSLATE("Wait for GDB connection..."), XRCID("DebugGDB"), CMDEN_NGDB_GBA },
    {wxT("DebugGDBBreak"), wxTRANSLATE("Break into GDB"), XRCID("DebugGDBBreak"), CMDEN_GDB },
    {wxT("DebugGDBDisconnect"), wxTRANSLATE("Disconnect GDB"), XRCID("DebugGDBDisconnect"), CMDEN_GDB },
    {wxT("DebugGDBLoad"), wxTRANSLATE("Load and wait for GDB..."), XRCID("DebugGDBLoad"), CMDEN_NGDB_ANY },
    {wxT("DecrGameSlot"), wxTRANSLATE("Decrease state slot number"), XRCID("DecrGameSlot"), CMDEN_GB|CMDEN_GBA },
    {wxT("DecreaseVolume"), wxTRANSLATE("Decrease volume"), XRCID("DecreaseVolume") },
    {wxT("DirectSoundA"), wxTRANSLATE("Direct Sound A (toggle)"), XRCID("DirectSoundA"), CMDEN_GBA },
    {wxT("DirectSoundB"), wxTRANSLATE("Direct Sound B (toggle)"), XRCID("DirectSoundB"), CMDEN_GBA },
    {wxT("Disassemble"), wxTRANSLATE("Disassemble..."), XRCID("Disassemble"), CMDEN_GB|CMDEN_GBA },
    {wxT("DisplayConfigure"), wxTRANSLATE("Display options..."), XRCID("DisplayConfigure"), CMDEN_NREC_ANY },
    {wxT("EXIT"), wxTRANSLATE("Exit"), wxID_EXIT },
    {wxT("EmulatorDirectories"), wxTRANSLATE("Directories..."), XRCID("EmulatorDirectories") },
    {wxT("EmulatorSpeedupToggle"), wxTRANSLATE("Turbo mode (toggle)"), XRCID("EmulatorSpeedupToggle"), CMDEN_GB|CMDEN_GBA },
    {wxT("ExportBatteryFile"), wxTRANSLATE("Export battery file..."), XRCID("ExportBatteryFile"), CMDEN_GB|CMDEN_GBA },
    {wxT("ExportGamesharkSnapshot"), wxTRANSLATE("Export GameShark snapshot..."), XRCID("ExportGamesharkSnapshot"), CMDEN_GBA },
    {wxT("FAQ"), wxTRANSLATE("VBA-M support forum"), XRCID("FAQ") },
    {wxT("FILE1"), wxTRANSLATE("Load recent ROM 1"), wxID_FILE1 },
    {wxT("FILE10"), wxTRANSLATE("Load recent ROM 10"), wxID_FILE10 },
    {wxT("FILE2"), wxTRANSLATE("Load recent ROM 2"), wxID_FILE2 },
    {wxT("FILE3"), wxTRANSLATE("Load recent ROM 3"), wxID_FILE3 },
    {wxT("FILE4"), wxTRANSLATE("Load recent ROM 4"), wxID_FILE4 },
    {wxT("FILE5"), wxTRANSLATE("Load recent ROM 5"), wxID_FILE5 },
    {wxT("FILE6"), wxTRANSLATE("Load recent ROM 6"), wxID_FILE6 },
    {wxT("FILE7"), wxTRANSLATE("Load recent ROM 7"), wxID_FILE7 },
    {wxT("FILE8"), wxTRANSLATE("Load recent ROM 8"), wxID_FILE8 },
    {wxT("FILE9"), wxTRANSLATE("Load recent ROM 9"), wxID_FILE9 },
    {wxT("GameBoyAdvanceConfigure"), wxTRANSLATE("Game Boy Advance options..."), XRCID("GameBoyAdvanceConfigure") },
    {wxT("GameBoyConfigure"), wxTRANSLATE("Game Boy options..."), XRCID("GameBoyConfigure") },
    {wxT("GeneralConfigure"), wxTRANSLATE("General options..."), XRCID("GeneralConfigure") },
    {wxT("IOViewer"), wxTRANSLATE("I/O Viewer..."), XRCID("IOViewer"), CMDEN_GBA },
    {wxT("ImportBatteryFile"), wxTRANSLATE("Import battery file..."), XRCID("ImportBatteryFile"), CMDEN_GB|CMDEN_GBA },
    {wxT("ImportGamesharkActionReplaySnapshot"), wxTRANSLATE("Import GameShark Action Replay snapshot..."), XRCID("ImportGamesharkActionReplaySnapshot"), CMDEN_GB|CMDEN_GBA },
    {wxT("ImportGamesharkCodeFile"), wxTRANSLATE("Import GameShark code file..."), XRCID("ImportGamesharkCodeFile"), CMDEN_GB|CMDEN_GBA },
    {wxT("IncrGameSlot"), wxTRANSLATE("Increase state slot number"), XRCID("IncrGameSlot"), CMDEN_GB|CMDEN_GBA },
    {wxT("IncrGameSlotSave"), wxTRANSLATE("Increase state slot number and save"), XRCID("IncrGameSlotSave"), CMDEN_GB|CMDEN_GBA },
    {wxT("IncreaseVolume"), wxTRANSLATE("Increase volume"), XRCID("IncreaseVolume") },
    {wxT("JoypadAutofireA"), wxTRANSLATE("Autofire A (toggle)"), XRCID("JoypadAutofireA") },
    {wxT("JoypadAutofireB"), wxTRANSLATE("Autofire B (toggle)"), XRCID("JoypadAutofireB") },
    {wxT("JoypadAutofireL"), wxTRANSLATE("Autofire L (toggle)"), XRCID("JoypadAutofireL") },
    {wxT("JoypadAutofireR"), wxTRANSLATE("Autofire R (toggle)"), XRCID("JoypadAutofireR") },
    {wxT("JoypadConfigure"), wxTRANSLATE("Joypad options..."), XRCID("JoypadConfigure") },
    {wxT("KeepCheats"), wxTRANSLATE("Do not change cheat list (toggle)"), XRCID("KeepCheats") },
    {wxT("KeepSaves"), wxTRANSLATE("Do not load battery saves (toggle)"), XRCID("KeepSaves") },
    {wxT("LanLink"), wxTRANSLATE("Start LAN link"), XRCID("LanLink"), CMDEN_LINK_ANY },
    {wxT("LinkConfigure"), wxTRANSLATE("Link options..."), XRCID("LinkConfigure") },
    {wxT("Load"), wxTRANSLATE("Load state..."), XRCID("Load"), CMDEN_GB|CMDEN_GBA },
    {wxT("LoadGame01"), wxTRANSLATE("Load saved state 1"), XRCID("LoadGame01"), CMDEN_SAVST },
    {wxT("LoadGame02"), wxTRANSLATE("Load saved state 2"), XRCID("LoadGame02"), CMDEN_SAVST },
    {wxT("LoadGame03"), wxTRANSLATE("Load saved state 3"), XRCID("LoadGame03"), CMDEN_SAVST },
    {wxT("LoadGame04"), wxTRANSLATE("Load saved state 4"), XRCID("LoadGame04"), CMDEN_SAVST },
    {wxT("LoadGame05"), wxTRANSLATE("Load saved state 5"), XRCID("LoadGame05"), CMDEN_SAVST },
    {wxT("LoadGame06"), wxTRANSLATE("Load saved state 6"), XRCID("LoadGame06"), CMDEN_SAVST },
    {wxT("LoadGame07"), wxTRANSLATE("Load saved state 7"), XRCID("LoadGame07"), CMDEN_SAVST },
    {wxT("LoadGame08"), wxTRANSLATE("Load saved state 8"), XRCID("LoadGame08"), CMDEN_SAVST },
    {wxT("LoadGame09"), wxTRANSLATE("Load saved state 9"), XRCID("LoadGame09"), CMDEN_SAVST },
    {wxT("LoadGame10"), wxTRANSLATE("Load saved state 10"), XRCID("LoadGame10"), CMDEN_SAVST },
    {wxT("LoadGameAutoLoad"), wxTRANSLATE("Auto load most recent save (toggle)"), XRCID("LoadGameAutoLoad") },
    {wxT("LoadGameRecent"), wxTRANSLATE("Load most recent save"), XRCID("LoadGameRecent"), CMDEN_SAVST },
    {wxT("LoadGameSlot"), wxTRANSLATE("Load current state slot"), XRCID("LoadGameSlot"), CMDEN_GB|CMDEN_GBA },
    {wxT("Logging"), wxTRANSLATE("Logging..."), XRCID("Logging"), CMDEN_GBA },
    {wxT("MapViewer"), wxTRANSLATE("Map Viewer..."), XRCID("MapViewer"), CMDEN_GB|CMDEN_GBA },
    {wxT("MemoryViewer"), wxTRANSLATE("Memory Viewer..."), XRCID("MemoryViewer"), CMDEN_GB|CMDEN_GBA },
    {wxT("NOOP"), wxTRANSLATE("Do nothing"), XRCID("NOOP"), CMDEN_NEVER },
    {wxT("NextFrame"), wxTRANSLATE("Next Frame"), XRCID("NextFrame"), CMDEN_GB|CMDEN_GBA },
    {wxT("OAMViewer"), wxTRANSLATE("OAM Viewer..."), XRCID("OAMViewer"), CMDEN_GB|CMDEN_GBA },
    {wxT("OPEN"), wxTRANSLATE("Open ROM..."), wxID_OPEN },
    {wxT("PaletteViewer"), wxTRANSLATE("Palette Viewer..."), XRCID("PaletteViewer"), CMDEN_GB|CMDEN_GBA },
    {wxT("Pause"), wxTRANSLATE("Pause (toggle)"), XRCID("Pause") },
    {wxT("PlayMovieStartPlaying"), wxTRANSLATE("Start playing movie..."), XRCID("PlayMovieStartPlaying"), CMDEN_NGREC|CMDEN_NGPLAY },
    {wxT("PlayMovieStopPlaying"), wxTRANSLATE("Stop playing movie"), XRCID("PlayMovieStopPlaying"), CMDEN_GPLAY },
    {wxT("RecentFreeze"), wxTRANSLATE("Freeze recent ROM list (toggle)"), XRCID("RecentFreeze") },
    {wxT("RecentReset"), wxTRANSLATE("Reset recent ROM list"), XRCID("RecentReset") },
    {wxT("RecordAVIStartRecording"), wxTRANSLATE("Start video recording..."), XRCID("RecordAVIStartRecording"), CMDEN_NVREC },
    {wxT("RecordAVIStopRecording"), wxTRANSLATE("Stop video recording"), XRCID("RecordAVIStopRecording"), CMDEN_VREC },
    {wxT("RecordMovieStartRecording"), wxTRANSLATE("Start game recording..."), XRCID("RecordMovieStartRecording"), CMDEN_NGREC },
    {wxT("RecordMovieStopRecording"), wxTRANSLATE("Stop game recording"), XRCID("RecordMovieStopRecording"), CMDEN_GREC },
    {wxT("RecordSoundStartRecording"), wxTRANSLATE("Start sound recording..."), XRCID("RecordSoundStartRecording"), CMDEN_NSREC },
    {wxT("RecordSoundStopRecording"), wxTRANSLATE("Stop sound recording"), XRCID("RecordSoundStopRecording"), CMDEN_SREC },
    {wxT("Reset"), wxTRANSLATE("Reset"), XRCID("Reset"), CMDEN_GB|CMDEN_GBA },
    {wxT("Rewind"), wxTRANSLATE("Rewind"), XRCID("Rewind"), CMDEN_REWIND },
    {wxT("RomInformation"), wxTRANSLATE("ROM information..."), XRCID("RomInformation"), CMDEN_GB|CMDEN_GBA },
    {wxT("Save"), wxTRANSLATE("Save state as..."), XRCID("Save"), CMDEN_GB|CMDEN_GBA },
    {wxT("SaveGame01"), wxTRANSLATE("Save state 1"), XRCID("SaveGame01"), CMDEN_GB|CMDEN_GBA },
    {wxT("SaveGame02"), wxTRANSLATE("Save state 2"), XRCID("SaveGame02"), CMDEN_GB|CMDEN_GBA },
    {wxT("SaveGame03"), wxTRANSLATE("Save state 3"), XRCID("SaveGame03"), CMDEN_GB|CMDEN_GBA },
    {wxT("SaveGame04"), wxTRANSLATE("Save state 4"), XRCID("SaveGame04"), CMDEN_GB|CMDEN_GBA },
    {wxT("SaveGame05"), wxTRANSLATE("Save state 5"), XRCID("SaveGame05"), CMDEN_GB|CMDEN_GBA },
    {wxT("SaveGame06"), wxTRANSLATE("Save state 6"), XRCID("SaveGame06"), CMDEN_GB|CMDEN_GBA },
    {wxT("SaveGame07"), wxTRANSLATE("Save state 7"), XRCID("SaveGame07"), CMDEN_GB|CMDEN_GBA },
    {wxT("SaveGame08"), wxTRANSLATE("Save state 8"), XRCID("SaveGame08"), CMDEN_GB|CMDEN_GBA },
    {wxT("SaveGame09"), wxTRANSLATE("Save state 9"), XRCID("SaveGame09"), CMDEN_GB|CMDEN_GBA },
    {wxT("SaveGame10"), wxTRANSLATE("Save state 10"), XRCID("SaveGame10"), CMDEN_GB|CMDEN_GBA },
    {wxT("SaveGameOldest"), wxTRANSLATE("Save state to oldest slot"), XRCID("SaveGameOldest"), CMDEN_GB|CMDEN_GBA },
    {wxT("SaveGameSlot"), wxTRANSLATE("Save current state slot"), XRCID("SaveGameSlot"), CMDEN_GB|CMDEN_GBA },
    {wxT("ScreenCapture"), wxTRANSLATE("Screen capture..."), XRCID("ScreenCapture"), CMDEN_GB|CMDEN_GBA },
    {wxT("SoundChannel1"), wxTRANSLATE("Sound Channel 1 (toggle)"), XRCID("SoundChannel1"), CMDEN_GB|CMDEN_GBA },
    {wxT("SoundChannel2"), wxTRANSLATE("Sound Channel 2 (toggle)"), XRCID("SoundChannel2"), CMDEN_GB|CMDEN_GBA },
    {wxT("SoundChannel3"), wxTRANSLATE("Sound Channel 3 (toggle)"), XRCID("SoundChannel3"), CMDEN_GB|CMDEN_GBA },
    {wxT("SoundChannel4"), wxTRANSLATE("Sound Channel 4 (toggle)"), XRCID("SoundChannel4"), CMDEN_GB|CMDEN_GBA },
    {wxT("SoundConfigure"), wxTRANSLATE("Sound options..."), XRCID("SoundConfigure"), CMDEN_NREC_ANY },
    {wxT("TileViewer"), wxTRANSLATE("Tile Viewer..."), XRCID("TileViewer"), CMDEN_GB|CMDEN_GBA },
    {wxT("ToggleFullscreen"), wxTRANSLATE("Full screen (toggle)"), XRCID("ToggleFullscreen") },
    {wxT("ToggleSound"), wxTRANSLATE("Enable/disable all sound channels"), XRCID("ToggleSound") },
    {wxT("VideoLayersBG0"), wxTRANSLATE("Video layer BG0 (toggle)"), XRCID("VideoLayersBG0"), CMDEN_GB|CMDEN_GBA },
    {wxT("VideoLayersBG1"), wxTRANSLATE("Video layer BG1 (toggle)"), XRCID("VideoLayersBG1"), CMDEN_GB|CMDEN_GBA },
    {wxT("VideoLayersBG2"), wxTRANSLATE("Video layer BG2 (toggle)"), XRCID("VideoLayersBG2"), CMDEN_GB|CMDEN_GBA },
    {wxT("VideoLayersBG3"), wxTRANSLATE("Video layer BG3 (toggle)"), XRCID("VideoLayersBG3"), CMDEN_GB|CMDEN_GBA },
    {wxT("VideoLayersOBJ"), wxTRANSLATE("Video layer OBJ (toggle)"), XRCID("VideoLayersOBJ"), CMDEN_GB|CMDEN_GBA },
    {wxT("VideoLayersOBJWIN"), wxTRANSLATE("Video layer OBJWIN (toggle)"), XRCID("VideoLayersOBJWIN"), CMDEN_GB|CMDEN_GBA },
    {wxT("VideoLayersReset"), wxTRANSLATE("Show all video layers"), XRCID("VideoLayersReset"), CMDEN_GB|CMDEN_GBA },
    {wxT("VideoLayersWIN0"), wxTRANSLATE("Video layer WIN0 (toggle)"), XRCID("VideoLayersWIN0"), CMDEN_GB|CMDEN_GBA },
    {wxT("VideoLayersWIN1"), wxTRANSLATE("Video layer WIN1 (toggle)"), XRCID("VideoLayersWIN1"), CMDEN_GB|CMDEN_GBA }
};
const int ncmds = sizeof(cmdtab) / sizeof(cmdtab[0]);
